baseURL = 'https://sols1st.github.io'
languageCode = 'zh-CN'
title = "Solsist's Blog"
theme = "only"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
style = "abap"
tabWidth = 4

[taxonomies]
tag = "tags"
category = "categories"

[params]
bio = "知ってることだけ"
github = "sols1st"
email = "sols1st@outlook.com"
